import type {
  PartnerProgramsSnapshot,
  ProductProgramLink,
  Program,
  Promotion,
} from "@/types/partner-programs";

const AGENCY = "tl-demo";
const BY = "seed";

function iso(d: string): string {
  return `${d}T12:00:00.000Z`;
}

function nowSeed(): string {
  return "2026-03-20T10:00:00.000Z";
}

/** Stable “today” for prototype promo windows (aligned with productDirectoryCommission). */
export const PARTNER_PROGRAMS_REFERENCE_ISO = "2026-03-24T12:00:00.000Z";

export const SEED_PROGRAMS: Program[] = [
  {
    id: "reg-virtuoso",
    name: "Virtuoso Preferred",
    network: "Virtuoso",
    type: "consortium",
    termsSummary: "10–15% commission on room revenue. Complimentary upgrades and amenities.",
    commissionRate: "10%",
    commissionType: "percentage",
    commissionCurrency: "EUR",
    amenities: ["room-upgrade", "breakfast", "hotel-credit", "early-checkin", "late-checkout"],
    hasPropertyLevelOverrides: true,
    agencyContact: { name: "Sarah Mitchell", email: "sarah@virtuoso.com", phone: "+1 555 0123" },
    agreementStart: "2024-01-01",
    renewalDate: "2026-12-31",
    status: "active",
    notes: null,
    agencyId: AGENCY,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
  },
  {
    id: "reg-fhr",
    name: "Fine Hotels & Resorts",
    network: "American Express",
    type: "consortium",
    termsSummary: "8–12% commission. Free breakfast, upgrade, late checkout, property credit.",
    commissionRate: "10%",
    commissionType: "percentage",
    commissionCurrency: "USD",
    amenities: ["breakfast", "room-upgrade", "late-checkout", "hotel-credit"],
    hasPropertyLevelOverrides: false,
    agencyContact: { name: "David Chen", email: "david@amextravel.com", phone: "+1 555 0456" },
    agreementStart: "2023-06-01",
    renewalDate: "2027-06-01",
    status: "active",
    notes: null,
    agencyId: AGENCY,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
  },
  {
    id: "reg-aman-direct",
    name: "Aman Direct",
    network: null,
    type: "direct",
    termsSummary: "12% flat on all bookings. Annual renewal.",
    commissionRate: "12%",
    commissionType: "percentage",
    commissionCurrency: "JPY",
    amenities: ["breakfast", "room-upgrade", "welcome-amenity"],
    hasPropertyLevelOverrides: false,
    agencyContact: { name: "Yuki Tanaka", email: "yuki@aman.com", phone: "+81 3 1234 5678" },
    agreementStart: "2025-01-01",
    renewalDate: "2026-04-05",
    status: "expiring",
    notes: "Renewal in flight",
    agencyId: AGENCY,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
  },
  {
    id: "reg-fs-pp",
    name: "Four Seasons Preferred Partners",
    network: "Four Seasons",
    type: "preferred_partner",
    termsSummary:
      "Commission on room revenue. Guaranteed upgrade on arrival, daily breakfast, $100 property credit.",
    commissionRate: "12%",
    commissionType: "percentage",
    commissionCurrency: "USD",
    amenities: ["room-upgrade", "breakfast", "spa-credit", "early-checkin", "late-checkout"],
    hasPropertyLevelOverrides: true,
    agencyContact: { name: "Kristin (DA Luxury Travel)", email: "kristin@daluxurytravel.com", phone: null },
    agreementStart: "2024-04-01",
    renewalDate: "2026-12-31",
    status: "active",
    notes: null,
    agencyId: AGENCY,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
  },
  {
    id: "reg-aman-pref",
    name: "Aman Preferred",
    network: "Aman",
    type: "direct",
    termsSummary: "Preferred partner amenities on qualifying bookings.",
    commissionRate: "10%",
    commissionType: "percentage",
    commissionCurrency: "USD",
    amenities: ["breakfast", "room-upgrade", "welcome-amenity"],
    hasPropertyLevelOverrides: false,
    agencyContact: { name: "Partners Desk", email: "partners@aman.com", phone: null },
    agreementStart: "2025-01-01",
    renewalDate: "2026-09-30",
    status: "active",
    notes: null,
    agencyId: AGENCY,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
  },
  {
    id: "reg-direct",
    name: "Direct Partnership",
    network: null,
    type: "direct",
    termsSummary: "Direct net rates.",
    commissionRate: "8%",
    commissionType: "percentage",
    commissionCurrency: "USD",
    amenities: ["welcome-amenity", "airport-transfer"],
    hasPropertyLevelOverrides: false,
    agencyContact: { name: "Reservations", email: "reservations@partner.com", phone: null },
    agreementStart: "2024-01-01",
    renewalDate: "2026-06-30",
    status: "active",
    notes: null,
    agencyId: AGENCY,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
  },
  {
    id: "reg-silversea",
    name: "Silversea Preferred Partner",
    network: "Silversea",
    type: "consortium",
    termsSummary: "Preferred partner benefits on sailings.",
    commissionRate: "15%",
    commissionType: "percentage",
    commissionCurrency: "EUR",
    amenities: ["dining-credit", "hotel-credit", "welcome-amenity"],
    hasPropertyLevelOverrides: false,
    agencyContact: { name: "Partnerships", email: "partnerships@silversea.com", phone: null },
    agreementStart: "2023-09-01",
    renewalDate: "2026-09-30",
    status: "active",
    notes: null,
    agencyId: AGENCY,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
  },
];

function link(
  id: string,
  programId: string,
  productId: string,
  opts: Partial<Omit<ProductProgramLink, "id" | "programId" | "productId">> = {}
): ProductProgramLink {
  return {
    id,
    programId,
    productId,
    commissionRate: opts.commissionRate ?? null,
    commissionType: opts.commissionType ?? null,
    currency: opts.currency ?? null,
    effectiveFrom: opts.effectiveFrom ?? iso("2025-01-01"),
    expiresAt: opts.expiresAt ?? null,
    contactName: opts.contactName ?? null,
    contactEmail: opts.contactEmail ?? null,
    contactPhone: opts.contactPhone ?? null,
    notes: opts.notes ?? null,
    amenities: opts.amenities ?? null,
    status: opts.status ?? "active",
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
  };
}

/** Initial links aligned with `productDirectoryMock` sample products. */
export const SEED_LINKS: ProductProgramLink[] = [
  link("lnk-001-v", "reg-virtuoso", "prod_001", {
    expiresAt: iso("2026-12-31"),
    commissionRate: null,
    contactEmail: "virtuoso@aman.com",
    status: "active",
  }),
  link("lnk-001-ap", "reg-aman-pref", "prod_001", {
    expiresAt: iso("2026-09-30"),
    commissionRate: null,
    status: "active",
  }),
  link("lnk-002-fs", "reg-fs-pp", "prod_002", {
    expiresAt: iso("2026-12-31"),
    commissionRate: null,
    contactEmail: "partnerships@fourseasons.com",
    status: "active",
  }),
  link("lnk-003-d", "reg-direct", "prod_003", {
    expiresAt: iso("2026-04-02"),
    commissionRate: null,
    status: "active",
  }),
  link("lnk-004-s", "reg-silversea", "prod_004", {
    expiresAt: iso("2026-09-30"),
    commissionRate: null,
    status: "active",
  }),
];

export const SEED_PROMOTIONS: Promotion[] = [
  {
    id: "promo-fs-q1",
    programId: "reg-fs-pp",
    productIds: ["prod_002"],
    name: "Spring override — 15%",
    rateValue: "15%",
    rateType: "percentage",
    stacksWithBase: false,
    bookingWindowStart: iso("2026-03-24"),
    bookingWindowEnd: iso("2026-06-30"),
    travelWindowStart: iso("2026-04-01"),
    travelWindowEnd: iso("2026-09-30"),
    volumeThreshold: null,
    volumeMetric: null,
    volumeRetroactive: false,
    eligibilityNotes: "Applies to new bookings in window.",
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
    updatedBy: BY,
  },
  {
    id: "promo-virt-bonus",
    programId: "reg-virtuoso",
    productIds: "all",
    name: "Q1 booking bonus",
    rateValue: "+2%",
    rateType: "percentage",
    stacksWithBase: true,
    bookingWindowStart: iso("2026-03-01"),
    bookingWindowEnd: iso("2026-06-30"),
    travelWindowStart: null,
    travelWindowEnd: null,
    volumeThreshold: null,
    volumeMetric: null,
    volumeRetroactive: false,
    eligibilityNotes: null,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
    updatedBy: BY,
  },
  {
    id: "promo-april-kickoff",
    programId: "reg-virtuoso",
    productIds: "all",
    name: "April booking bonus",
    rateValue: "+1%",
    rateType: "percentage",
    stacksWithBase: true,
    bookingWindowStart: iso("2026-04-01"),
    bookingWindowEnd: iso("2026-08-31"),
    travelWindowStart: null,
    travelWindowEnd: null,
    volumeThreshold: null,
    volumeMetric: null,
    volumeRetroactive: false,
    eligibilityNotes: null,
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
    updatedBy: BY,
  },
  {
    id: "promo-narrow-window",
    programId: "reg-direct",
    productIds: "all",
    name: "Short booking window closeout",
    rateValue: "9%",
    rateType: "percentage",
    stacksWithBase: false,
    bookingWindowStart: iso("2026-03-01"),
    bookingWindowEnd: iso("2026-04-03"),
    travelWindowStart: null,
    travelWindowEnd: null,
    volumeThreshold: null,
    volumeMetric: null,
    volumeRetroactive: false,
    eligibilityNotes: "Prototype — narrow window for notification demo.",
    createdBy: BY,
    createdAt: nowSeed(),
    updatedAt: nowSeed(),
    updatedBy: BY,
  },
];

export function createPartnerProgramsSeedSnapshot(): PartnerProgramsSnapshot {
  return {
    programs: SEED_PROGRAMS.map((p) => ({ ...p })),
    links: SEED_LINKS.map((l) => ({ ...l })),
    promotions: SEED_PROMOTIONS.map((p) => ({ ...p })),
  };
}
