/**
 * Knowledge Vault mock data.
 */

import {
  DataSourceType,
  DocumentType,
  type DataSource,
  type KnowledgeDocument,
  type IngestionHealth,
  type KnowledgeDocumentListParams,
  type KnowledgeDocumentListResponse,
} from "@/types/knowledge-vault";

const now = new Date();
const twoMinAgo = new Date(now.getTime() - 2 * 60 * 1000).toISOString();
const oneHourAgo = new Date(now.getTime() - 60 * 60 * 1000).toISOString();
const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString();

export function getMockDataSources(): DataSource[] {
  return [
    {
      id: "src-gdrive",
      name: "Google Drive",
      source_type: DataSourceType.GoogleDrive,
      icon: "Cloud",
      description: "Shared drives and team folders",
      status: "connected",
      last_sync: twoMinAgo,
      document_count: 312,
      total_size_mb: 1240,
      sync_frequency: "daily",
      health_score: 95,
      connected_at: "2025-01-15T10:00:00Z",
    },
    {
      id: "src-claromentis",
      name: "Claromentis",
      source_type: DataSourceType.Claromentis,
      icon: "Database",
      description: "Intranet and internal docs",
      status: "connected",
      last_sync: oneHourAgo,
      document_count: 487,
      total_size_mb: 2100,
      sync_frequency: "daily",
      health_score: 78,
      connected_at: "2025-02-01T09:00:00Z",
    },
    {
      id: "src-manual",
      name: "Manual Uploads",
      source_type: DataSourceType.ManualUpload,
      icon: "Upload",
      description: "Advisor and agency uploads",
      status: "connected",
      last_sync: now.toISOString(),
      document_count: 34,
      total_size_mb: 89,
      sync_frequency: "manual",
      health_score: 100,
      connected_at: "2024-06-01T00:00:00Z",
    },
    {
      id: "src-virtuoso",
      name: "Virtuoso Network",
      source_type: DataSourceType.Virtuoso,
      icon: "Globe",
      description: "Virtuoso partner content",
      status: "connected",
      last_sync: oneWeekAgo,
      document_count: 14,
      total_size_mb: 45,
      sync_frequency: "weekly",
      health_score: 45,
      connected_at: "2025-03-01T12:00:00Z",
    },
    {
      id: "src-email",
      name: "Email Ingestion",
      source_type: DataSourceType.Email,
      icon: "Mail",
      description: "Email attachments and threads",
      status: "disconnected",
      last_sync: "",
      document_count: 0,
      total_size_mb: 0,
      sync_frequency: "manual",
      health_score: 0,
      connected_at: "",
    },
  ];
}

function d(daysAgo: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

export function getMockDocuments(): KnowledgeDocument[] {
  return [
    {
      id: "doc-1",
      title: "Maldives Destination Guide 2026",
      source_id: "src-gdrive",
      source_type: DataSourceType.GoogleDrive,
      source_name: "Google Drive",
      data_layer: "agency",
      document_type: DocumentType.DestinationGuide,
      file_type: "pdf",
      file_size_kb: 2400,
      content_summary: "Comprehensive guide to Maldivian resorts, transfers, and best practices for luxury travel. Includes One&Only, Four Seasons, and Soneva properties with seasonal rates and availability tips.",
      tags: ["luxury", "beach", "wellness", "Asia"],
      ingestion_status: "indexed",
      ingested_at: d(1),
      last_updated: d(1),
      freshness: "fresh",
      quality_score: 92,
      linked_products: [{ id: "p1", name: "One&Only Reethi Rah" }],
      linked_vics: [],
    },
    {
      id: "doc-2",
      title: "Tuscany & Chianti Travel Guide",
      source_id: "src-gdrive",
      source_type: DataSourceType.GoogleDrive,
      source_name: "Google Drive",
      data_layer: "agency",
      document_type: DocumentType.DestinationGuide,
      file_type: "pdf",
      file_size_kb: 1800,
      content_summary: "Wine regions, villa stays, and cultural highlights. Covers Belmond Villa San Michele, Castello di Ama, and recommended itineraries for 5–7 day trips.",
      tags: ["Europe", "wine", "culture", "gastronomy"],
      ingestion_status: "indexed",
      ingested_at: d(3),
      last_updated: d(3),
      freshness: "fresh",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-3",
      title: "Four Seasons Global Rate Sheet 2026",
      source_id: "src-gdrive",
      source_type: DataSourceType.GoogleDrive,
      source_name: "Google Drive",
      data_layer: "enable",
      document_type: DocumentType.RateSheet,
      file_type: "xlsx",
      file_size_kb: 520,
      content_summary: "Commissionable rates for Four Seasons properties worldwide. Includes seasonal adjustments and group rates.",
      tags: ["rates", "commission", "luxury"],
      ingestion_status: "indexed",
      ingested_at: d(5),
      last_updated: d(5),
      freshness: "fresh",
      linked_products: [{ id: "p2", name: "Four Seasons George V" }],
      linked_vics: [],
    },
    {
      id: "doc-4",
      title: "DMC Partner Framework Agreement",
      source_id: "src-gdrive",
      source_type: DataSourceType.GoogleDrive,
      source_name: "Google Drive",
      data_layer: "agency",
      document_type: DocumentType.Contract,
      file_type: "pdf",
      file_size_kb: 340,
      content_summary: "Standard terms and commission structure for DMC partnerships. Valid through December 2026.",
      tags: ["contract", "policy", "commission"],
      ingestion_status: "indexed",
      ingested_at: d(10),
      last_updated: d(10),
      freshness: "recent",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-5",
      title: "Luxury Sales Training Module 1",
      source_id: "src-gdrive",
      source_type: DataSourceType.GoogleDrive,
      source_name: "Google Drive",
      data_layer: "agency",
      document_type: DocumentType.TrainingMaterial,
      file_type: "pdf",
      file_size_kb: 2100,
      content_summary: "Introduction to selling high-end travel: consultative approach, objection handling, and closing techniques.",
      tags: ["training", "luxury", "sales"],
      ingestion_status: "indexed",
      ingested_at: d(14),
      last_updated: d(14),
      freshness: "recent",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-6",
      title: "Aman Tokyo — Property Profile",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "agency",
      document_type: DocumentType.PropertyProfile,
      file_type: "pdf",
      file_size_kb: 1200,
      content_summary: "Full property overview: 84 rooms, dining, spa, and preferred partner benefits. Ideal for city stays and pre/post Japan itineraries.",
      tags: ["luxury", "city", "Asia", "wellness"],
      ingestion_status: "indexed",
      ingested_at: d(2),
      last_updated: d(2),
      freshness: "fresh",
      quality_score: 88,
      linked_products: [{ id: "p3", name: "Aman Tokyo" }],
      linked_vics: [{ id: "v1", name: "Jean-Christophe Chopin" }],
    },
    {
      id: "doc-7",
      title: "Belmond Caruso Ravello — Property Overview",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "agency",
      document_type: DocumentType.PropertyProfile,
      file_type: "pdf",
      file_size_kb: 980,
      content_summary: "Cliffside hotel in Ravello with villa rooms and pool. Wedding and group capabilities. Best rates for Virtuoso advisors.",
      tags: ["Europe", "luxury", "wedding"],
      ingestion_status: "indexed",
      ingested_at: d(4),
      last_updated: d(4),
      freshness: "fresh",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-8",
      title: "One&Only Reethi Rah — Fact Sheet",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "agency",
      document_type: DocumentType.PropertyProfile,
      file_type: "pdf",
      file_size_kb: 760,
      content_summary: "Villa types, dining, spa, and family offerings. Includes seasonal offers and upgrade paths.",
      tags: ["luxury", "beach", "family", "wellness"],
      ingestion_status: "indexed",
      ingested_at: d(6),
      last_updated: d(6),
      freshness: "fresh",
      linked_products: [{ id: "p1", name: "One&Only Reethi Rah" }],
      linked_vics: [{ id: "v2", name: "Camille Signoles" }],
    },
    {
      id: "doc-9",
      title: "Q1 2026 Partner Newsletter",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "agency",
      document_type: DocumentType.Newsletter,
      file_type: "pdf",
      file_size_kb: 420,
      content_summary: "New properties, rate updates, and FAM trip calendar. Highlights Aman, Belmond, and Four Seasons programs.",
      tags: ["newsletter", "Virtuoso", "rates"],
      ingestion_status: "indexed",
      ingested_at: d(8),
      last_updated: d(8),
      freshness: "fresh",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-10",
      title: "March 2026 Advisor Briefing",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "agency",
      document_type: DocumentType.Newsletter,
      file_type: "docx",
      file_size_kb: 180,
      content_summary: "Internal briefing on policy changes, commission deadlines, and upcoming training sessions.",
      tags: ["policy", "internal", "training"],
      ingestion_status: "indexed",
      ingested_at: d(12),
      last_updated: d(12),
      freshness: "recent",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-11",
      title: "Travel Advisory & Insurance Policy",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "agency",
      document_type: DocumentType.Policy,
      file_type: "pdf",
      file_size_kb: 310,
      content_summary: "Agency policy on advising clients on travel insurance, advisories, and cancellation. Must-read for all advisors.",
      tags: ["policy", "advisory"],
      ingestion_status: "indexed",
      ingested_at: d(20),
      last_updated: d(20),
      freshness: "recent",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-12",
      title: "Preferred Partner Directory 2026",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "enable",
      document_type: DocumentType.PartnerDirectory,
      file_type: "pdf",
      file_size_kb: 890,
      content_summary: "Full list of preferred partners with contact details, tiers, and key benefits. Updated quarterly.",
      tags: ["Virtuoso", "partner", "directory"],
      ingestion_status: "indexed",
      ingested_at: d(25),
      last_updated: d(25),
      freshness: "aging",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-13",
      title: "Internal memo — Acuity rollout",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "agency",
      document_type: DocumentType.InternalMemo,
      file_type: "docx",
      file_size_kb: 95,
      content_summary: "Rollout plan for VIC Intelligence (Acuity) and how to use it in client conversations.",
      tags: ["internal", "training", "acuity"],
      ingestion_status: "indexed",
      ingested_at: d(30),
      last_updated: d(30),
      freshness: "aging",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-14",
      title: "Q4 Client Report — Chopin Family",
      source_id: "src-manual",
      source_type: DataSourceType.ManualUpload,
      source_name: "Manual Uploads",
      data_layer: "advisor",
      document_type: DocumentType.ClientReport,
      file_type: "pdf",
      file_size_kb: 450,
      content_summary: "Summary of travel spend, preferences, and recommendations for the Chopin family. Includes Monaco and Nice stays.",
      tags: ["client", "luxury", "Europe"],
      ingestion_status: "indexed",
      ingested_at: d(2),
      last_updated: d(2),
      freshness: "fresh",
      uploaded_by: "user-1",
      uploaded_by_name: "You",
      linked_products: [],
      linked_vics: [{ id: "v1", name: "Jean-Christophe Chopin" }],
    },
    {
      id: "doc-15",
      title: "Luxury Maldives Brochure 2026",
      source_id: "src-manual",
      source_type: DataSourceType.ManualUpload,
      source_name: "Manual Uploads",
      data_layer: "agency",
      document_type: DocumentType.MarketingCollateral,
      file_type: "pdf",
      file_size_kb: 3200,
      content_summary: "Marketing brochure for Maldives portfolio: One&Only, Four Seasons, Soneva. High-res imagery and key selling points.",
      tags: ["marketing", "beach", "luxury", "Maldives"],
      ingestion_status: "indexed",
      ingested_at: d(5),
      last_updated: d(5),
      freshness: "fresh",
      linked_products: [{ id: "p1", name: "One&Only Reethi Rah" }],
      linked_vics: [],
    },
    {
      id: "doc-16",
      title: "Bali Visa & Entry Requirements — May 2026",
      source_id: "src-manual",
      source_type: DataSourceType.ManualUpload,
      source_name: "Manual Uploads",
      data_layer: "agency",
      document_type: DocumentType.TravelAdvisory,
      file_type: "pdf",
      file_size_kb: 210,
      content_summary: "Updated visa-on-arrival and e-VOA requirements for Bali. Effective May 2026. Share with clients traveling to Indonesia.",
      tags: ["advisory", "Bali", "Asia", "visa"],
      ingestion_status: "indexed",
      ingested_at: d(1),
      last_updated: d(1),
      freshness: "fresh",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-17",
      title: "Virtuoso Preferred Hotels Rate Card",
      source_id: "src-virtuoso",
      source_type: DataSourceType.Virtuoso,
      source_name: "Virtuoso Network",
      data_layer: "enable",
      document_type: DocumentType.RateSheet,
      file_type: "xlsx",
      file_size_kb: 680,
      content_summary: "Preferred and exclusive rates for Virtuoso hotel partners. Commission tiers and booking windows.",
      tags: ["Virtuoso", "rates", "commission"],
      ingestion_status: "indexed",
      ingested_at: d(40),
      last_updated: d(40),
      freshness: "aging",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-18",
      title: "Virtuoso Europe Rates Q2 2026",
      source_id: "src-virtuoso",
      source_type: DataSourceType.Virtuoso,
      source_name: "Virtuoso Network",
      data_layer: "enable",
      document_type: DocumentType.RateSheet,
      file_type: "pdf",
      file_size_kb: 380,
      content_summary: "European hotel and DMC rates. Includes Belmond, Aman, and regional DMCs.",
      tags: ["Virtuoso", "Europe", "rates"],
      ingestion_status: "indexed",
      ingested_at: d(50),
      last_updated: d(50),
      freshness: "stale",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-19",
      title: "Virtuoso Partner Directory Extract",
      source_id: "src-virtuoso",
      source_type: DataSourceType.Virtuoso,
      source_name: "Virtuoso Network",
      data_layer: "enable",
      document_type: DocumentType.PartnerDirectory,
      file_type: "pdf",
      file_size_kb: 1200,
      content_summary: "Extract of key Virtuoso partners with contact info and program highlights.",
      tags: ["Virtuoso", "partner", "directory"],
      ingestion_status: "indexed",
      ingested_at: d(55),
      last_updated: d(55),
      freshness: "stale",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-20",
      title: "Virtuoso Advisor Training — Luxury Selling",
      source_id: "src-virtuoso",
      source_type: DataSourceType.Virtuoso,
      source_name: "Virtuoso Network",
      data_layer: "agency",
      document_type: DocumentType.TrainingMaterial,
      file_type: "pdf",
      file_size_kb: 1500,
      content_summary: "Certification module on luxury travel selling. Covers positioning, storytelling, and closing.",
      tags: ["training", "Virtuoso", "luxury"],
      ingestion_status: "processing",
      last_updated: d(0),
      freshness: "fresh",
      linked_products: [],
      linked_vics: [],
    },
    {
      id: "doc-21",
      title: "Monaco GP Weekend — Client Itinerary Draft",
      source_id: "src-gdrive",
      source_type: DataSourceType.GoogleDrive,
      source_name: "Google Drive",
      data_layer: "advisor",
      document_type: DocumentType.InternalMemo,
      file_type: "docx",
      file_size_kb: 120,
      content_summary: "Draft itinerary and notes for Jean-Christophe Chopin Monaco Grand Prix trip. Pending final confirmations.",
      tags: ["adventure", "Europe", "luxury", "motorsport"],
      ingestion_status: "pending",
      last_updated: d(0),
      freshness: "fresh",
      linked_products: [],
      linked_vics: [{ id: "v1", name: "Jean-Christophe Chopin" }],
    },
    {
      id: "doc-22",
      title: "Legacy DMC Contract (expired)",
      source_id: "src-claromentis",
      source_type: DataSourceType.Claromentis,
      source_name: "Claromentis",
      data_layer: "agency",
      document_type: DocumentType.Contract,
      file_type: "pdf",
      file_size_kb: 280,
      content_summary: "Previous DMC agreement. Superseded by new framework. Kept for reference.",
      tags: ["contract", "policy"],
      ingestion_status: "failed",
      last_updated: d(100),
      freshness: "stale",
      linked_products: [],
      linked_vics: [],
    },
  ];
}

export function getMockIngestionHealth(): IngestionHealth {
  return {
    total_documents: 847,
    indexed: 823,
    pending: 12,
    processing: 5,
    failed: 7,
    stale: 12,
    last_full_sync: twoMinAgo,
    avg_freshness_days: 14,
  };
}

export function getMockDocumentById(id: string): KnowledgeDocument | null {
  return getMockDocuments().find((d) => d.id === id) ?? null;
}

export function filterMockDocuments(
  params: KnowledgeDocumentListParams
): KnowledgeDocumentListResponse {
  let list = [...getMockDocuments()];

  if (params.source_id) list = list.filter((d) => d.source_id === params.source_id);
  if (params.data_layer) list = list.filter((d) => d.data_layer === params.data_layer);
  if (params.document_type) list = list.filter((d) => d.document_type === params.document_type);
  if (params.freshness) list = list.filter((d) => d.freshness === params.freshness);
  if (params.ingestion_status) list = list.filter((d) => d.ingestion_status === params.ingestion_status);
  if (params.tags?.length) {
    const tagSet = new Set(params.tags);
    list = list.filter((d) => d.tags.some((t) => tagSet.has(t)));
  }
  if (params.search) {
    const q = params.search.toLowerCase();
    list = list.filter(
      (d) =>
        d.title.toLowerCase().includes(q) ||
        (d.content_summary ?? "").toLowerCase().includes(q) ||
        d.tags.some((t) => t.toLowerCase().includes(q))
    );
  }

  const sortBy = params.sort_by ?? "last_updated";
  const order = params.sort_order ?? "desc";
  list.sort((a, b) => {
    let aVal: string | number = a.last_updated;
    let bVal: string | number = b.last_updated;
    if (sortBy === "title") {
      aVal = a.title;
      bVal = b.title;
    } else if (sortBy === "quality_score") {
      aVal = a.quality_score ?? 0;
      bVal = b.quality_score ?? 0;
    } else if (sortBy === "file_size_kb") {
      aVal = a.file_size_kb;
      bVal = b.file_size_kb;
    }
    const cmp = typeof aVal === "string" ? String(aVal).localeCompare(String(bVal)) : aVal - (bVal as number);
    return order === "asc" ? cmp : -cmp;
  });

  const total = list.length;
  const page = Math.max(1, params.page ?? 1);
  const limit = Math.max(1, params.limit ?? 20);
  const start = (page - 1) * limit;
  list = list.slice(start, start + limit);

  return { documents: list, total };
}
