import type {
  DirectoryCollectionOption,
  DirectoryExternalSearchMeta,
  DirectoryPartnerProgram,
  DirectoryProduct,
  DirectoryProductCollectionRef,
} from "@/types/product-directory";
import { TEAM_EVERYONE_ID } from "@/types/teams";
import { getRepFirmLinksForProduct } from "./productDirectoryRepFirmMock";
import { getAdvisoriesForProduct } from "./productDirectoryAdvisoryMock";

/** Default collection for products saved from chat / external search. */
export const DIRECTORY_EXTERNAL_COLLECTION_ID = "col-external";

/**
 * Mock advisor id whose `MOCK_DIRECTORY_PRODUCTS` rows include External Search membership.
 * Other advisors get an empty External Search bucket until they save (or you call `applyAddProductToExternalSearch`).
 */
export const DIRECTORY_EXTERNAL_SEARCH_MOCK_SEED_ADVISOR_ID = "1";

/** Demo metadata for “saved from chat / external search” (keys = directory product ids). */
export const EXTERNAL_SEARCH_META: Record<string, DirectoryExternalSearchMeta> = {
  prod_009: {
    savedAt: "2026-02-15T10:30:00Z",
    savedBy: "Marco Pellegrini",
    searchQuery: "luxury resort Saint Lucia all-inclusive",
    sourceConversation: 9004,
  },
  "prod-well-001": {
    savedAt: "2026-03-02T14:15:00Z",
    savedBy: "Claire Dubois",
    searchQuery: "wellness retreat Europe medical spa",
  },
  prod_007: {
    savedAt: "2026-03-10T09:45:00Z",
    savedBy: "Hana Yoshida",
    searchQuery: "patagonia trekking luxury lodge",
  },
  prod_008: {
    savedAt: "2026-03-18T16:00:00Z",
    savedBy: "James Whitfield",
    searchQuery: "luxury cruise Dubai Oman Arabian Gulf",
    sourceConversation: 9006,
  },
};

export function getExternalSearchMeta(productId: string): DirectoryExternalSearchMeta | undefined {
  return EXTERNAL_SEARCH_META[productId];
}

/** Merges persisted chat/search saves over built-in demo metadata. */
export function resolveExternalSearchMeta(
  productId: string,
  persisted?: Record<string, DirectoryExternalSearchMeta>
): DirectoryExternalSearchMeta | undefined {
  const p = persisted?.[productId];
  if (p) return p;
  return EXTERNAL_SEARCH_META[productId];
}

function formatSavedAtForTooltip(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

export function externalSearchSavedTooltip(
  productId: string,
  persisted?: Record<string, DirectoryExternalSearchMeta>
): string | undefined {
  const m = resolveExternalSearchMeta(productId, persisted);
  if (!m) return undefined;
  const q = m.searchQuery ?? "external search";
  const who = m.savedBy?.trim() ? m.savedBy : "Advisor";
  const when = m.savedAt ? formatSavedAtForTooltip(m.savedAt) : "recently";
  let out = `Saved ${when} by ${who} — "${q}"`;
  if (m.sourceConversation != null) {
    out += ` · Chat #${m.sourceConversation}`;
  }
  return out;
}

export function cloneDirectoryProduct(p: DirectoryProduct): DirectoryProduct {
  return {
    ...p,
    imageGalleryUrls: p.imageGalleryUrls ? [...p.imageGalleryUrls] : undefined,
    collectionIds: [...p.collectionIds],
    collections: p.collections.map((c) => ({ ...c })),
    partnerPrograms: p.partnerPrograms.map((pp) => ({
      ...pp,
      activePromotions: pp.activePromotions.map((x) => ({ ...x })),
    })),
    commissionAdvisories: p.commissionAdvisories?.map((advisory) => ({ ...advisory })),
    repFirmLinks: (p.repFirmLinks ?? []).map((link) => ({ ...link })),
    agencyContacts: p.agencyContacts.map((c) => ({ ...c })),
  };
}

const promo = (
  id: string,
  effectiveRate: number,
  bookingStart: string,
  bookingEnd: string,
  travelStart: string,
  travelEnd: string
) => ({ id, effectiveRate, bookingStart, bookingEnd, travelStart, travelEnd });

function makeProgram(
  id: string,
  programId: string,
  programName: string,
  commissionRate: number | null,
  expiryDate: string | null,
  contact?: string,
  opts: Partial<
    Pick<DirectoryPartnerProgram, "amenities" | "amenityTags" | "activePromotions" | "registryStatus" | "status">
  > = {}
): DirectoryPartnerProgram {
  const program: DirectoryPartnerProgram = {
    id,
    name: programName,
    programId,
    programName,
    commissionRate,
    expiryDate,
    activePromotions: opts.activePromotions ?? [],
    amenities: opts.amenities ?? `${programName} partner rate and amenities apply.`,
    amenityTags: opts.amenityTags ?? [],
    commissionType: "percentage",
    registryStatus: opts.registryStatus,
    status: opts.status ?? "active",
  };
  if (contact != null && contact !== "") program.contact = contact;
  return program;
}

const BASE_MOCK_DIRECTORY_PRODUCTS: Omit<DirectoryProduct, "repFirmLinks" | "repFirmCount">[] = [
  {
    id: "prod_001",
    name: "Aman Tokyo",
    imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=240&fit=crop",
    imageGalleryUrls: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=400&h=240&fit=crop",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=400&h=240&fit=crop",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&h=240&fit=crop",
    ],
    website: "https://www.aman.com/hotels/aman-tokyo",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 4,
    starRating: 5,
    roomCount: 84,
    tags: ["urban", "zen", "design", "fine-dining"],
    location: "Tokyo, Japan",
    city: "Tokyo",
    country: "Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    type: "hotel",
    region: "Asia-Pacific",
    description: "Ultra-luxury contemporary design with traditional Japanese aesthetics",
    scope: "agency",
    baseCommissionRate: 10,
    effectiveCommissionRate: 10,
    activePromotion: null,
    commissionRate: 10,
    partnerProgramCount: 2,
    collectionCount: 2,
    collectionIds: ["col_001", "col_002"],
    partnerPrograms: [
      makeProgram("prog_001", "prog-virtuoso", "Virtuoso", 10, "2026-12-31", "virtuoso@aman.com", {
        amenities:
          "Room upgrade on availability, daily breakfast for 2, $100 hotel credit, early check-in / late check-out.",
        amenityTags: ["room-upgrade", "breakfast", "hotel-credit", "early-checkin", "late-checkout"],
      }),
      makeProgram("prog_001b", "prog-preferred", "Aman Preferred", 10, "2026-09-30", "partners@aman.com", {
        amenityTags: ["breakfast", "room-upgrade", "welcome-amenity"],
      }),
    ],
    agencyContacts: [
      {
        id: "contact_001",
        name: "Yuki Tanaka",
        role: "Relationship Manager",
        email: "yuki@aman.com",
        phone: "+81-3-XXXX-XXXX",
        note: "Prefers Japanese communication",
        addedBy: "Janet",
        addedById: "1",
      },
      {
        id: "contact_001_pending",
        name: "Kenji Sato",
        role: "Sales Coordinator",
        email: "kenji.sato@aman.com",
        phone: "—",
        pendingUpgrade: true,
        upgradedById: "2",
        upgradedByName: "Alex",
        addedBy: "Alex",
        addedById: "2",
      },
    ],
    collections: [
      { id: "col_001", name: "Japan Shortlist", scope: "private" },
      { id: "col_002", name: "Agency Favorites", scope: TEAM_EVERYONE_ID },
    ],
    hasTeamData: true,
    hasAdvisorNotes: true,
    addedAt: "2025-11-15T10:00:00Z",
    updatedAt: "2026-03-18T14:30:00Z",
  },
  {
    id: "prod_002",
    name: "Four Seasons Bora Bora",
    imageUrl: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=400&h=240&fit=crop",
    website: "https://www.fourseasons.com/borabora/",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    starRating: 5,
    roomCount: 107,
    tags: ["overwater", "lagoon", "honeymoon"],
    location: "Bora Bora, French Polynesia",
    city: "Bora Bora",
    country: "French Polynesia",
    latitude: -16.5004,
    longitude: -151.7415,
    type: "hotel",
    region: "South Pacific",
    description: "Overwater bungalows with private pools overlooking turquoise lagoon",
    scope: "agency",
    baseCommissionRate: 12,
    effectiveCommissionRate: 15,
    activePromotion: promo("promo_001", 15, "2026-03-24", "2026-06-30", "2026-04-01", "2026-09-30"),
    commissionRate: 15,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col_001"],
    partnerPrograms: [
      makeProgram(
        "prog_002",
        "prog-preferred",
        "Four Seasons Preferred Partners",
        12,
        "2026-12-31",
        "partnerships@fourseasons.com",
        {
          amenities: "Upgrade at check-in, daily breakfast, spa credit on longer stays, early/late check-in/out.",
          amenityTags: ["room-upgrade", "breakfast", "spa-credit", "early-checkin", "late-checkout"],
          activePromotions: [
            promo("apromo_001", 15, "2026-03-24", "2026-06-30", "2026-04-01", "2026-09-30"),
          ],
        }
      ),
    ],
    agencyContacts: [],
    collections: [{ id: "col_001", name: "Japan Shortlist", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2025-12-01T09:00:00Z",
    updatedAt: "2026-02-20T11:00:00Z",
  },
  {
    id: "prod_003",
    name: "&Beyond Serengeti",
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    location: "Serengeti, Tanzania",
    city: "Serengeti",
    country: "Tanzania",
    latitude: -2.3333,
    longitude: 34.8333,
    type: "experience",
    region: "Africa",
    description: "Multi-day safari adventure with expert naturalists and luxury camps",
    scope: "agency",
    baseCommissionRate: 8,
    effectiveCommissionRate: 8,
    activePromotion: null,
    commissionRate: 8,
    partnerProgramCount: 1,
    collectionCount: 0,
    collectionIds: [],
    partnerPrograms: [
      makeProgram("prog_003", "prog-direct", "Direct Partnership", 8, "2026-06-30", "reservations@andbeyond.com", {
        amenityTags: ["welcome-amenity", "airport-transfer"],
      }),
    ],
    agencyContacts: [],
    collections: [],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2025-10-20T12:00:00Z",
    updatedAt: "2026-01-08T09:00:00Z",
  },
  {
    id: "prod_004",
    name: "Silversea Cruises",
    imageUrl: "https://images.unsplash.com/photo-1548574505-5e239809ee19?w=400&h=240&fit=crop",
    location: "Mediterranean Sea",
    city: "At sea",
    country: "Italy",
    latitude: 41.9,
    longitude: 12.5,
    type: "cruise",
    region: "Europe",
    description: "All-inclusive ultra-luxury cruises with Michelin-starred dining",
    scope: "agency",
    baseCommissionRate: 15,
    effectiveCommissionRate: 15,
    activePromotion: null,
    commissionRate: 15,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col_003"],
    partnerPrograms: [
      makeProgram(
        "prog_004",
        "prog-consortium",
        "Silversea Preferred Partner",
        15,
        "2026-09-30",
        "partnerships@silversea.com",
        {
          amenities: "Shipboard credit, specialty dining, pre-cruise hotel, dedicated partner desk.",
          amenityTags: ["dining-credit", "hotel-credit", "welcome-amenity"],
        }
      ),
    ],
    agencyContacts: [],
    collections: [{ id: "col_003", name: "Europe Specialists — Cruises", scope: "team-europe" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2025-09-05T08:00:00Z",
    updatedAt: "2026-03-01T15:00:00Z",
  },
  {
    id: "prod_005",
    name: "Bali Luxury DMC — Dima",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&h=240&fit=crop",
    website: "https://example.com/baliluxdmc",
    tier: "premium",
    priceTier: "$$$",
    enrichmentScore: 4,
    destinations: "Bali, Lombok, Komodo",
    tags: ["dmc", "indonesia", "fit"],
    location: "Ubud, Indonesia",
    city: "Ubud",
    country: "Indonesia",
    latitude: -8.5069,
    longitude: 115.2625,
    type: "dmc",
    region: "Asia-Pacific",
    description: "Full-service destination management for high-net-worth Indonesia itineraries",
    scope: "private",
    baseCommissionRate: 12,
    effectiveCommissionRate: 12,
    activePromotion: null,
    commissionRate: 12,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col_002"],
    partnerPrograms: [
      makeProgram("prog_dima", "prog-direct", "Direct", 12, "2026-12-31", "trade@baliluxdmc.com", {
        amenities: "Dedicated FIT desk, custom itinerary design, 24/7 ground support.",
        amenityTags: ["airport-transfer", "welcome-amenity"],
      }),
    ],
    agencyContacts: [
      {
        id: "c_dima",
        name: "Dima Wijaya",
        role: "Managing Director",
        email: "dima@baliluxdmc.com",
        phone: "+62-361-XXXX",
      },
    ],
    collections: [{ id: "col_002", name: "Agency Favorites", scope: TEAM_EVERYONE_ID }],
    hasTeamData: true,
    hasAdvisorNotes: true,
    addedAt: "2025-08-12T14:00:00Z",
    updatedAt: "2026-02-28T10:20:00Z",
  },
  {
    id: "prod_006",
    name: "Rosewood Mayakoba",
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=240&fit=crop",
    location: "Riviera Maya, Mexico",
    city: "Playa del Carmen",
    country: "Mexico",
    latitude: 20.6843,
    longitude: -87.0723,
    type: "hotel",
    region: "North America",
    description: "Jungle-meets-lagoon suites with world-class spa and dining",
    scope: "agency",
    baseCommissionRate: 11,
    effectiveCommissionRate: 11,
    activePromotion: null,
    commissionRate: 11,
    partnerProgramCount: 2,
    collectionCount: 0,
    collectionIds: [],
    partnerPrograms: [
      makeProgram("prog_rw", "prog-preferred", "Rosewood Elite", 11, "2026-12-01", "partners@rosewood.com", {
        amenityTags: ["breakfast", "room-upgrade", "spa-credit", "late-checkout"],
      }),
      makeProgram("prog_rw_fhr", "prog-fhr", "Amex FHR", 7, "2026-08-01", "fhr@rosewood.com", {
        amenities: "Complimentary breakfast, guaranteed 4pm late checkout, room upgrade, $100 property credit.",
        amenityTags: ["breakfast", "late-checkout", "room-upgrade", "hotel-credit"],
      }),
    ],
    agencyContacts: [],
    collections: [],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2025-11-22T11:30:00Z",
    updatedAt: "2026-03-05T08:45:00Z",
  },
  {
    id: "prod_007",
    name: "Explora Patagonia",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&h=240&fit=crop",
    location: "Torres del Paine, Chile",
    city: "Torres del Paine",
    country: "Chile",
    latitude: -50.9423,
    longitude: -73.4068,
    type: "experience",
    region: "South America",
    description: "Lodge-based expeditions with guided hikes and gaucho culture",
    scope: "agency",
    baseCommissionRate: 9,
    effectiveCommissionRate: 9,
    activePromotion: null,
    commissionRate: 9,
    partnerProgramCount: 1,
    collectionCount: 2,
    collectionIds: ["col_004", DIRECTORY_EXTERNAL_COLLECTION_ID],
    partnerPrograms: [
      makeProgram("prog_ex", "prog-direct", "Explora Direct", 9, "2027-01-15", "trade@explora.com", {
        amenityTags: ["breakfast", "welcome-amenity", "airport-transfer"],
      }),
    ],
    agencyContacts: [],
    collections: [
      { id: "col_004", name: "Adventure Picks", scope: "private" },
      { id: DIRECTORY_EXTERNAL_COLLECTION_ID, name: "External Search", scope: "private" },
    ],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2025-07-01T09:00:00Z",
    updatedAt: "2026-02-11T16:00:00Z",
  },
  {
    id: "prod_008",
    name: "Regent Seven Seas — Arabia",
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=240&fit=crop",
    location: "Dubai to Muscat",
    city: "Dubai",
    country: "UAE",
    latitude: 25.2048,
    longitude: 55.2708,
    type: "cruise",
    region: "Middle East",
    description: "Ultra-luxury small-ship sailing with all-inclusive shore experiences",
    scope: "agency",
    baseCommissionRate: 14,
    effectiveCommissionRate: 14,
    activePromotion: null,
    commissionRate: 14,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: [DIRECTORY_EXTERNAL_COLLECTION_ID],
    partnerPrograms: [
      makeProgram("prog_rss", "prog-consortium", "Regent Partner", 14, "2026-04-10", "partners@rssc.com", {
        registryStatus: "expiring-soon",
        amenityTags: ["dining-credit", "hotel-credit", "complimentary-night"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: DIRECTORY_EXTERNAL_COLLECTION_ID, name: "External Search", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-01-02T10:00:00Z",
    updatedAt: "2026-03-12T13:20:00Z",
  },
  {
    id: "prod_009",
    name: "Jade Mountain Resort",
    imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
    location: "Soufrière, Saint Lucia",
    city: "Soufrière",
    country: "Saint Lucia",
    latitude: 13.9094,
    longitude: -61.0734,
    type: "hotel",
    region: "Caribbean",
    description: "Iconic open-wall sanctuaries overlooking the Pitons",
    scope: "agency",
    baseCommissionRate: null,
    effectiveCommissionRate: null,
    activePromotion: null,
    commissionRate: null,
    partnerProgramCount: 0,
    collectionCount: 1,
    collectionIds: [DIRECTORY_EXTERNAL_COLLECTION_ID],
    partnerPrograms: [],
    agencyContacts: [],
    collections: [{ id: DIRECTORY_EXTERNAL_COLLECTION_ID, name: "External Search", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: true,
    addedAt: "2025-06-18T07:00:00Z",
    updatedAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "prod-villa-001",
    name: "Villa Treville — Positano",
    imageUrl: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=400&h=240&fit=crop",
    website: "https://www.treville.com",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 4,
    bedrooms: 3,
    maxGuests: 8,
    tags: ["amalfi", "private", "pool"],
    location: "Positano, Italy",
    city: "Positano",
    country: "Italy",
    latitude: 40.6281,
    longitude: 14.484,
    type: "villa",
    region: "Europe",
    description:
      "Clifftop private villa overlooking the Amalfi Coast. 3 suites, infinity pool, dedicated staff.",
    scope: "agency",
    baseCommissionRate: 12,
    effectiveCommissionRate: 12,
    activePromotion: null,
    commissionRate: 12,
    partnerProgramCount: 1,
    collectionCount: 0,
    collectionIds: [],
    partnerPrograms: [
      makeProgram("ppl-villa-001", "prog-direct", "Direct", 12, null, undefined, {
        amenities:
          "Complimentary airport transfer, welcome hamper, daily housekeeping, private chef available.",
        amenityTags: ["airport-transfer", "welcome-amenity"],
      }),
    ],
    agencyContacts: [],
    collections: [],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-02-05T14:00:00Z",
    updatedAt: "2026-03-22T09:15:00Z",
  },
  {
    id: "prod-rest-001",
    name: "Mirazur — Menton",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=240&fit=crop",
    website: "https://www.mirazur.fr",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    michelinStars: 3,
    cuisine: "Modern French / coastal",
    tags: ["michelin", "riviera", "tasting-menu"],
    location: "Menton, France",
    city: "Menton",
    country: "France",
    latitude: 43.7863,
    longitude: 7.5072,
    type: "restaurant",
    region: "Europe",
    description:
      "Mauro Colagreco's 3-Michelin-star restaurant. Reservations typically 2-3 months out — we have direct access.",
    scope: "agency",
    baseCommissionRate: null,
    effectiveCommissionRate: null,
    activePromotion: null,
    commissionRate: null,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: [DIRECTORY_EXTERNAL_COLLECTION_ID],
    partnerPrograms: [
      makeProgram("ppl-rest-001", "prog-direct", "Direct", null, null, undefined, {
        amenities: "Priority reservation, complimentary aperitif, kitchen tour when available.",
        amenityTags: ["welcome-amenity", "dining-credit"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: DIRECTORY_EXTERNAL_COLLECTION_ID, name: "External Search", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: true,
    addedAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-20T17:00:00Z",
  },
  {
    id: "prod-well-001",
    name: "SHA Wellness Clinic — Alicante",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=240&fit=crop",
    website: "https://www.shawellnessclinic.com",
    tier: "luxury",
    priceTier: "$$$$",
    enrichmentScore: 4,
    specialty: "Integrative medicine, detox, longevity",
    tags: ["wellness", "medical", "spa"],
    location: "Alicante, Spain",
    city: "Alicante",
    country: "Spain",
    latitude: 38.6347,
    longitude: -0.135,
    type: "wellness",
    region: "Europe",
    description:
      "Integrative medical wellness resort. Programs from 4 to 28 days covering detox, weight management, and longevity.",
    scope: "agency",
    baseCommissionRate: 8,
    effectiveCommissionRate: 8,
    activePromotion: null,
    commissionRate: 8,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: [DIRECTORY_EXTERNAL_COLLECTION_ID],
    partnerPrograms: [
      makeProgram("ppl-well-001", "prog-preferred", "Preferred Partner", 8, "2026-12-31", undefined, {
        amenities: "Complimentary initial consultation, room upgrade, late checkout, 10% off treatments.",
        amenityTags: ["room-upgrade", "late-checkout", "spa-credit"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: DIRECTORY_EXTERNAL_COLLECTION_ID, name: "External Search", scope: "private" }],
    hasTeamData: false,
    hasAdvisorNotes: true,
    addedAt: "2026-02-14T08:30:00Z",
    updatedAt: "2026-03-19T11:00:00Z",
  },
  {
    id: "prod-trans-001",
    name: "VistaJet — Global Charter",
    imageUrl: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=400&h=240&fit=crop",
    website: "https://www.vistajet.com",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    vehicleType: "Private jet (Global fleet)",
    capacity: "Up to 14 guests per aircraft",
    tags: ["aviation", "charter", "global"],
    location: "Dubai, UAE",
    city: "Global",
    country: "UAE",
    latitude: 25.2532,
    longitude: 55.3657,
    type: "transport",
    region: "Middle East",
    description: "On-demand private aviation. Guaranteed availability within 24 hours to any destination worldwide.",
    scope: "agency",
    baseCommissionRate: 5,
    effectiveCommissionRate: 5,
    activePromotion: null,
    commissionRate: 5,
    partnerProgramCount: 1,
    collectionCount: 0,
    collectionIds: [],
    partnerPrograms: [
      makeProgram("ppl-trans-001", "prog-direct", "Direct", 5, null, undefined, {
        amenities: "Preferred advisor rates, 10% off first booking, dedicated flight coordinator.",
        amenityTags: ["welcome-amenity"],
      }),
    ],
    agencyContacts: [],
    collections: [],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2025-12-20T12:00:00Z",
    updatedAt: "2026-03-21T14:00:00Z",
  },
  {
    id: "prod-amanvari",
    name: "Amanvari",
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=240&fit=crop",
    website: "https://www.aman.com/hotels/amanvari",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    starRating: 5,
    roomCount: 36,
    tags: ["Opening 2026", "Beach", "Desert", "Ultra Luxury"],
    location: "Baja Peninsula, Mexico",
    city: "Baja Peninsula",
    country: "Mexico",
    latitude: 23.45,
    longitude: -109.78,
    type: "hotel",
    region: "Latin America",
    description: "Aman's first resort in Mexico, set on 2,300 acres of pristine Pacific coastline on the Baja Peninsula. Amanvari features 36 freestanding pavilions with panoramic ocean views, an 18-hole golf course, equestrian center, and an expansive Aman Spa. Opening 2026.",
    scope: "agency",
    baseCommissionRate: 12,
    effectiveCommissionRate: 12,
    activePromotion: null,
    commissionRate: 12,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col-2026-openings"],
    partnerPrograms: [
      makeProgram("prog-amanvari", "prog-aman-direct", "Aman Direct", 12, "2027-12-31", "partners@aman.com", {
        amenityTags: ["room-upgrade", "breakfast", "welcome-amenity"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: "col-2026-openings", name: "2026 Openings", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "prod-waldorf-london",
    name: "Waldorf Astoria London Admiralty Arch",
    imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=240&fit=crop",
    website: "https://www.waldorfastoria.com/london",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    starRating: 5,
    roomCount: 112,
    tags: ["Opening 2026", "City", "Historic", "Ultra Luxury"],
    location: "London, UK",
    city: "London",
    country: "United Kingdom",
    latitude: 51.507,
    longitude: -0.128,
    type: "hotel",
    region: "Europe",
    description: "Housed within the iconic Grade I-listed Admiralty Arch on The Mall, this landmark conversion brings Waldorf Astoria to one of London's most prestigious addresses. Features views over Trafalgar Square and direct access to St James's Park. Opening 2026.",
    scope: "agency",
    baseCommissionRate: 10,
    effectiveCommissionRate: 10,
    activePromotion: null,
    commissionRate: 10,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col-2026-openings"],
    partnerPrograms: [
      makeProgram("prog-waldorf-london", "prog-hilton-impresario", "Hilton Impresario", 10, "2027-12-31", "partnerships@hilton.com", {
        amenityTags: ["room-upgrade", "breakfast", "welcome-amenity"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: "col-2026-openings", name: "2026 Openings", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "prod-four-seasons-mykonos",
    name: "Four Seasons Mykonos",
    imageUrl: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=400&h=240&fit=crop",
    website: "https://www.fourseasons.com/mykonos/",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    starRating: 5,
    roomCount: 120,
    tags: ["Opening 2026", "Beach", "Island", "Ultra Luxury"],
    location: "Mykonos, Greece",
    city: "Mykonos",
    country: "Greece",
    latitude: 37.42,
    longitude: 25.35,
    type: "hotel",
    region: "Europe",
    description: "Four Seasons' debut on Mykonos brings the brand's refined hospitality to the Cyclades. Perched on the island's southern coast, the resort features multiple infinity pools, a signature Greek-Mediterranean restaurant, and a spa with sweeping Aegean views. Opening 2026.",
    scope: "agency",
    baseCommissionRate: 10,
    effectiveCommissionRate: 10,
    activePromotion: null,
    commissionRate: 10,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col-2026-openings"],
    partnerPrograms: [
      makeProgram("prog-fs-mykonos", "prog-fs-preferred", "Four Seasons Preferred Partners", 10, "2027-12-31", "partnerships@fourseasons.com", {
        amenityTags: ["room-upgrade", "breakfast", "spa-credit"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: "col-2026-openings", name: "2026 Openings", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "prod-six-senses-london",
    name: "Six Senses London",
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=240&fit=crop",
    website: "https://www.sixsenses.com/london",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    starRating: 5,
    roomCount: 110,
    tags: ["Opening 2026", "City", "Wellness", "Ultra Luxury"],
    location: "London, United Kingdom",
    city: "London",
    country: "United Kingdom",
    latitude: 51.512,
    longitude: -0.09,
    type: "hotel",
    region: "Europe",
    description: "Six Senses makes its London debut in a landmark building, bringing its wellness-first philosophy to the city. Features an extensive urban spa, rooftop restaurant with panoramic views, and the brand's signature sustainability program. Opening 2026.",
    scope: "agency",
    baseCommissionRate: 8,
    effectiveCommissionRate: 8,
    activePromotion: null,
    commissionRate: 8,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col-2026-openings"],
    partnerPrograms: [
      makeProgram("prog-six-senses-london", "prog-ihg-luxury", "IHG Luxury & Lifestyle", 8, "2027-12-31", "partnerships@sixsenses.com", {
        amenityTags: ["room-upgrade", "spa-credit", "welcome-amenity"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: "col-2026-openings", name: "2026 Openings", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "prod-orient-express-venezia",
    name: "Orient Express Venezia",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=240&fit=crop",
    website: "https://www.orient-express.com/venezia",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    starRating: 5,
    roomCount: 42,
    tags: ["Opening 2026", "City", "Historic", "Ultra Luxury"],
    location: "Venice, Italy",
    city: "Venice",
    country: "Italy",
    latitude: 45.445,
    longitude: 12.333,
    type: "hotel",
    region: "Europe",
    description: "The first Orient Express hotel occupies the magnificent Palazzo Donà Giovannelli on the Grand Canal. A masterful restoration blending Venetian Gothic architecture with contemporary luxury, featuring canal-front dining, a courtyard garden, and artisan wellness experiences. Opening 2026.",
    scope: "agency",
    baseCommissionRate: 12,
    effectiveCommissionRate: 12,
    activePromotion: null,
    commissionRate: 12,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col-2026-openings"],
    partnerPrograms: [
      makeProgram("prog-orient-venezia", "prog-accor-hera", "Accor HERA", 12, "2027-12-31", "partnerships@accor.com", {
        amenityTags: ["room-upgrade", "breakfast", "welcome-amenity"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: "col-2026-openings", name: "2026 Openings", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "prod-seven-seas-prestige",
    name: "Seven Seas Prestige — Regent",
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=240&fit=crop",
    website: "https://www.rssc.com/ships/seven-seas-prestige",
    tier: "ultra-luxury",
    priceTier: "$$$$$",
    enrichmentScore: 5,
    roomCount: 434,
    tags: ["Launching 2026", "All-Inclusive", "Ultra Luxury"],
    location: "Global",
    city: "At sea",
    country: "Global",
    type: "cruise",
    region: "Global",
    cruiseLine: "Regent Seven Seas",
    destinations: "Mediterranean, Caribbean, Asia",
    description: "Regent Seven Seas Cruises' newest ship and the first of its Prestige Class. Offering 434 all-suite accommodations with one of the highest guest-to-space ratios in the industry. All-inclusive luxury with specialty dining, a world-class spa, and curated shore excursions. Launching December 2026.",
    scope: "agency",
    baseCommissionRate: 16,
    effectiveCommissionRate: 16,
    activePromotion: null,
    commissionRate: 16,
    partnerProgramCount: 1,
    collectionCount: 1,
    collectionIds: ["col-2026-openings"],
    partnerPrograms: [
      makeProgram("prog-seven-seas-prestige", "prog-regent-direct", "Regent Direct", 16, "2027-12-31", "partnerships@rssc.com", {
        amenityTags: ["dining-credit", "welcome-amenity", "complimentary-night"],
      }),
    ],
    agencyContacts: [],
    collections: [{ id: "col-2026-openings", name: "2026 Openings", scope: "private" }],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "prod-dominique-debay",
    name: "Dominique Debay",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=240&fit=crop",
    website: "https://www.dominiquedebay.com",
    tags: ["Rep Firm", "Europe", "Indian Ocean", "Hotels", "DMCs"],
    specialty: "Asia Pacific & Indian Ocean luxury independents",
    location: "Paris, France",
    city: "Paris",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    type: "rep_firm",
    region: "Europe",
    description: "Boutique hotel and DMC representation firm covering luxury independents across Europe, Indian Ocean, and beyond. Represents both hotels and destination management companies, with deep relationships in France, Italy, and the Indian subcontinent.",
    scope: "agency",
    baseCommissionRate: null,
    effectiveCommissionRate: null,
    activePromotion: null,
    commissionRate: null,
    partnerProgramCount: 0,
    collectionCount: 0,
    collectionIds: [],
    partnerPrograms: [],
    agencyContacts: [],
    collections: [],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "prod-lush-experiences",
    name: "LUSH Experiences",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=240&fit=crop",
    tags: ["Rep Firm", "Global", "Hotels", "Experiences"],
    specialty: "Europe & Middle East luxury hotels",
    location: "New York, United States",
    city: "New York",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    type: "rep_firm",
    region: "North America",
    description: "LUSH Experiences represents a curated portfolio of luxury hotels and destination services across Europe and the Middle East. Known for strong advisor relationships and hands-on support for complex itineraries.",
    scope: "agency",
    baseCommissionRate: null,
    effectiveCommissionRate: null,
    activePromotion: null,
    commissionRate: null,
    partnerProgramCount: 0,
    collectionCount: 0,
    collectionIds: [],
    partnerPrograms: [],
    agencyContacts: [],
    collections: [],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "prod-index-select",
    name: "Index Select",
    imageUrl: "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=400&h=240&fit=crop",
    tags: ["Rep Firm", "Americas", "Caribbean", "Hotels", "Boutique"],
    specialty: "Americas & Caribbean luxury independents",
    location: "New York, United States",
    city: "New York",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    type: "rep_firm",
    region: "North America",
    description: "Index Select represents a carefully curated collection of independent luxury hotels, boutique properties, and distinctive experiences across the Americas and Caribbean.",
    scope: "agency",
    baseCommissionRate: null,
    effectiveCommissionRate: null,
    activePromotion: null,
    commissionRate: null,
    partnerProgramCount: 0,
    collectionCount: 0,
    collectionIds: [],
    partnerPrograms: [],
    agencyContacts: [],
    collections: [],
    hasTeamData: true,
    hasAdvisorNotes: false,
    addedAt: "2026-03-30T10:00:00Z",
    updatedAt: "2026-03-30T10:00:00Z",
  },
];

export const MOCK_DIRECTORY_PRODUCTS: DirectoryProduct[] = BASE_MOCK_DIRECTORY_PRODUCTS.map((product) => {
  const repFirmLinks = getRepFirmLinksForProduct(product.id);
  const advisories = getAdvisoriesForProduct(product.id);
  return {
    ...product,
    repFirmLinks,
    repFirmCount: repFirmLinks.length,
    commissionAdvisories: advisories,
    activeAdvisoryCount: advisories.filter((a) => a.status === "active").length,
  };
});

export const MOCK_DIRECTORY_COLLECTIONS: DirectoryCollectionOption[] = [
  {
    id: DIRECTORY_EXTERNAL_COLLECTION_ID,
    name: "External Search",
    description: "Products saved from chat and external search",
    scope: "private",
    ownerId: "1",
    ownerName: "Janet",
    teamId: null,
    productIds: ["prod_009", "prod-well-001", "prod_007", "prod_008"],
    isSystem: true,
    icon: "search",
    createdAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "col_001",
    name: "Japan Shortlist",
    description: "Hotels and experiences for Japan-bound VICs.",
    scope: "private",
    ownerId: "1",
    ownerName: "Janet",
    teamId: null,
    productIds: ["prod_001", "prod_002"],
  },
  {
    id: "col_002",
    name: "Agency Favorites",
    description: "Agency-wide preferred partners and properties.",
    scope: "team",
    ownerId: "system",
    ownerName: "Kristin",
    teamId: TEAM_EVERYONE_ID,
    teamName: "Everyone",
    productIds: ["prod_001", "prod_005"],
  },
  {
    id: "col_003",
    name: "Europe Specialists — Cruises",
    description: "Cruise lines and sailings curated by the Europe team.",
    scope: "team",
    ownerId: "admin",
    ownerName: "Demo Admin",
    teamId: "team-europe",
    teamName: "Europe Specialists",
    productIds: ["prod_004"],
  },
  {
    id: "col_004",
    name: "Adventure Picks",
    description: "Active and expedition-style options.",
    scope: "private",
    ownerId: "1",
    ownerName: "Janet",
    teamId: null,
    productIds: ["prod_007"],
  },
  {
    id: "col-2026-openings",
    name: "2026 Openings",
    description: "Newly opening luxury hotels, resorts, and cruises in 2026.",
    scope: "private",
    ownerId: "1",
    ownerName: "Janet",
    teamId: null,
    productIds: ["prod-amanvari", "prod-waldorf-london", "prod-four-seasons-mykonos", "prod-six-senses-london", "prod-orient-express-venezia", "prod-seven-seas-prestige"],
  },
];

/** Per-advisor catalog clone: External Search is owned by `advisorUserId`; seed demo data only for {@link DIRECTORY_EXTERNAL_SEARCH_MOCK_SEED_ADVISOR_ID}. */
export function cloneMockDirectoryCatalogForAdvisor(
  advisorUserId: string,
  advisorDisplayName: string
): { products: DirectoryProduct[]; collections: DirectoryCollectionOption[] } {
  const ownsSeed = advisorUserId === DIRECTORY_EXTERNAL_SEARCH_MOCK_SEED_ADVISOR_ID;
  const seedExternal = MOCK_DIRECTORY_COLLECTIONS.find((x) => x.id === DIRECTORY_EXTERNAL_COLLECTION_ID);
  const seedProductIds = seedExternal?.productIds ? [...seedExternal.productIds] : [];

  const collections: DirectoryCollectionOption[] = MOCK_DIRECTORY_COLLECTIONS.map((c) => {
    const base: DirectoryCollectionOption = { ...c, productIds: c.productIds ? [...c.productIds] : undefined };
    if (c.id !== DIRECTORY_EXTERNAL_COLLECTION_ID) return base;
    return {
      ...base,
      ownerId: advisorUserId,
      ownerName: advisorDisplayName,
      productIds: ownsSeed ? seedProductIds : [],
    };
  });

  const products: DirectoryProduct[] = MOCK_DIRECTORY_PRODUCTS.map((p) => {
    const copy = cloneDirectoryProduct(p);
    if (ownsSeed) return copy;
    if (!copy.collectionIds.includes(DIRECTORY_EXTERNAL_COLLECTION_ID)) return copy;
    const nextIds = copy.collectionIds.filter((id) => id !== DIRECTORY_EXTERNAL_COLLECTION_ID);
    const nextRefs = copy.collections.filter((x) => x.id !== DIRECTORY_EXTERNAL_COLLECTION_ID);
    return {
      ...copy,
      collectionIds: nextIds,
      collections: nextRefs,
      collectionCount: nextIds.length,
    };
  });

  return { products, collections };
}

/** Regions shown in filter + derived union from products. */
export const DIRECTORY_REGION_PRESETS = [
  "Africa",
  "Asia-Pacific",
  "Caribbean",
  "Europe",
  "Middle East",
  "North America",
  "South America",
  "South Pacific",
] as const;

export function getDirectoryProductById(id: string): DirectoryProduct | undefined {
  return MOCK_DIRECTORY_PRODUCTS.find((p) => p.id === id);
}

export function buildDirectoryCollectionRefs(
  ids: string[],
  all: DirectoryCollectionOption[]
): DirectoryProductCollectionRef[] {
  return ids.map((id) => {
    const c = all.find((x) => x.id === id);
    if (!c) return { id, name: id, scope: "private" };
    const scope: DirectoryProductCollectionRef["scope"] =
      c.scope === "private" ? "private" : (c.teamId ?? "team");
    return { id: c.id, name: c.name, scope };
  });
}
