import type { RepFirm, RepFirmProductLink } from "@/types/rep-firm";
import { migrateRepFirmRecord } from "@/lib/repFirmMigrate";

/** Legacy-shaped rows — normalized through migrateRepFirmRecord. */
const RAW_LEGACY_REP_FIRMS: unknown[] = [
  {
    id: "rf-lush-experiences",
    name: "LUSH Experiences",
    tagline: "Curate · Inspire · Influence",
    website: "https://www.lushexperiences.com",
    regions: ["Europe", "Middle East", "Caribbean"],
    productTypes: ["hotel", "villa", "restaurant"],
    propertyCount: 40,
    scope: "enable",
    status: "active",
    contactName: "Heidi LaRusso",
  },
  {
    id: "rf-index-select",
    name: "Index Select",
    tagline: "Boutique global hospitality agency",
    website: "https://www.indexselect.com",
    regions: ["Americas", "Caribbean"],
    productTypes: ["hotel", "villa"],
    propertyCount: 22,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-the-dmc-collection",
    name: "The DMC Collection",
    tagline: "Premier destination management partnerships",
    regions: ["Europe", "Asia"],
    productTypes: ["dmc", "experience"],
    propertyCount: 45,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-cruise-specialists-international",
    name: "Cruise Specialists International",
    tagline: "Global luxury cruise representation",
    regions: ["Global"],
    productTypes: ["cruise"],
    propertyCount: 18,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-nota-bene-global",
    name: "Nota Bene Global",
    tagline: "Ultra-luxury bespoke travel for UHNW clients",
    website: "https://www.notabeneglobal.com",
    regions: ["Europe", "Americas"],
    productTypes: ["hotel", "villa"],
    propertyCount: 31,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-traveller-made",
    name: "Traveller Made",
    tagline: "Global luxury travel community & representation",
    website: "https://www.travellermade.com",
    regions: ["Global"],
    productTypes: ["hotel", "experience", "restaurant"],
    propertyCount: 55,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-beyond-green",
    name: "Beyond Green",
    tagline: "Eco-first prestigious luxury travel",
    website: "https://www.staybeyondgreen.com",
    regions: ["Global"],
    productTypes: ["hotel", "wellness"],
    propertyCount: 50,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-kiwi-collection",
    name: "Kiwi Collection",
    tagline: "Hand-picked luxury hotels worldwide",
    website: "https://www.kiwicollection.com",
    regions: ["Global"],
    productTypes: ["hotel", "villa"],
    propertyCount: 40,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-preferred-hotels-resorts",
    name: "Preferred Hotels & Resorts",
    tagline: "World's largest independent hotel brand",
    website: "https://www.preferredhotels.com",
    regions: ["Global"],
    productTypes: ["hotel"],
    propertyCount: 650,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-slh",
    name: "Small Luxury Hotels (SLH)",
    tagline: "Independently spirited luxury hotels",
    website: "https://www.slh.com",
    regions: ["Global"],
    productTypes: ["hotel"],
    propertyCount: 520,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-lhw",
    name: "Leading Hotels of the World (LHW)",
    tagline: "Uncommon luxury since 1928",
    website: "https://www.lhw.com",
    regions: ["Global"],
    productTypes: ["hotel"],
    propertyCount: 400,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-janine-cifelli",
    name: "Janine Cifelli Representation",
    tagline: "Luxury hotel representation",
    website: "janinecifelli.com",
    portalUrl: "https://www.janinecifelli.com/travel-advisor",
    regions: ["Global"],
    productTypes: ["hotel"],
    propertyCount: 18,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-jmak",
    name: "JMAK",
    tagline: "Boutique hospitality sales & marketing",
    website: "https://www.jmak.com",
    regions: ["Global"],
    productTypes: ["hotel"],
    propertyCount: 24,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-muse-collection",
    name: "Muse Collection",
    tagline: "Curated luxury portfolios",
    website: "https://www.muse-collection.com",
    regions: ["Global"],
    productTypes: ["hotel", "villa"],
    propertyCount: 32,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-passages-distinction",
    name: "Passages of Distinction",
    tagline: "Luxury hotel representation",
    website: "https://www.passagesofdistinction.com",
    regions: ["Global"],
    productTypes: ["hotel"],
    propertyCount: 28,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-selected-escapes",
    name: "Selected Escapes",
    tagline: "Bespoke luxury representation",
    website: "https://www.selectedescapes.com",
    regions: ["Europe", "Asia"],
    productTypes: ["hotel", "dmc"],
    propertyCount: 20,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-wanderluxe-destinations",
    name: "Wanderluxe Destinations",
    tagline: "Independent luxury collections",
    website: "https://www.wanderluxedestinations.com",
    regions: ["Global"],
    productTypes: ["hotel", "villa"],
    propertyCount: 15,
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-beyond-collection",
    name: "The Beyond Collection",
    tagline: "Ultra-luxury hotel curation",
    website: "https://www.wearebeyond.com",
    regions: ["Global"],
    productTypes: ["hotel"],
    propertyCount: 22,
    scope: "enable",
    status: "active",
  },
];

/** Additional TravelLustre / Kristin inventory rows (day-zero seed). */
const RAW_KRISTIN_EXTRA: unknown[] = [
  {
    id: "rf-joanne-kurtz-ahlers",
    name: "Joanne Kurtz-Ahlers",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "hiddendoorwaystravel.com",
    scope: "enable",
    status: "prospect",
  },
  {
    id: "rf-waterstone-dod",
    name: "Marcel Vasquez — Waterstone / Destinations of Distinction",
    regions: ["Americas", "Europe"],
    productTypes: ["hotel", "dmc"],
    website: "waterstonemarketing.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-mjl-select",
    name: "Mario Leon — MJL Select",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "mjlselect.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-claudia-de-rin",
    name: "Claudia de Rin",
    regions: ["Europe"],
    productTypes: ["hotel", "villa"],
    website: "claudiadarin.it",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-bennett-mercado",
    name: "Cheryl Bennet — Bennett Mercado",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "bennettmercado.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-all-about-reps",
    name: "Yina Munoz — All About Reps",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "allaboutreps.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-rebecca-recommends",
    name: "Emer Mortell — Rebecca Recommends",
    regions: ["Europe"],
    productTypes: ["hotel"],
    website: "rebecca-recommends.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-set-collection",
    name: "Sue Fergerson — The Set Collection",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "thesetcollection.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-independently-yours",
    name: "Vincent Padolina + Salvatore Galati — Independently Yours",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "independently-yours.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-eos-hospitality",
    name: "EOS Hospitality",
    regions: ["Americas"],
    productTypes: ["hotel"],
    website: "eoshospitality.com",
    scope: "enable",
    status: "inactive",
  },
  {
    id: "rf-terra-collection",
    name: "Terra Collection",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "terratvl.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-antipodal",
    name: "Antipodal",
    regions: ["Asia", "Oceania"],
    productTypes: ["hotel"],
    website: "antipodal.net",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-luxury-boutique-collections",
    name: "Nunzio Giannone — Luxury Boutique Collections",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "luxuryboutiquecollections.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-ptg-calliope",
    name: "Lindsey MacLean — PTG / Calliope",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "ptgconsulting.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-wanderlux-collection",
    name: "Wanderlux Collection",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "wanderluxcollection.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-creative-destinations",
    name: "Jean-Pierre Jonqua — Creative Destinations",
    regions: ["Global"],
    productTypes: ["dmc"],
    website: "creativedestinations.net",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-travel-kinship",
    name: "Becky Harris — Travel Kinship",
    regions: ["Global"],
    productTypes: ["dmc"],
    website: "travelkinship.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-myths-muses",
    name: "Myths & Muses",
    regions: ["Europe"],
    productTypes: ["hotel"],
    website: "mythsandmuses.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-tl-portfolio",
    name: "Tina Lyra — TL Portfolio",
    regions: ["Europe"],
    productTypes: ["hotel"],
    website: "tlportfolio.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-reiimagine-collection",
    name: "Elaine Macy — Reiimagine Collection",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "reiimagine.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-buchhalter-international",
    name: "Buchhalter International Group",
    regions: ["Global"],
    productTypes: ["hotel"],
    website: "buchhalterinternationalgroup.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-andbeyond",
    name: "&Beyond",
    regions: ["Africa", "Asia", "Americas"],
    productTypes: ["hotel", "dmc", "experience"],
    website: "andbeyond.com",
    scope: "enable",
    status: "active",
  },
  {
    id: "rf-corbo-collection",
    name: "Corbo Collection",
    regions: ["Europe"],
    productTypes: ["hotel"],
    website: "corbocollection.com",
    scope: "enable",
    status: "active",
  },
];

/** Prototype-only: rich rows so the Rep Firms tab shows contacts, HQ, portals, Lux badges, etc. */
const REP_FIRM_DEMO_PATCH: Record<string, Partial<RepFirm>> = {
  "rf-lush-experiences": {
    representativeNames: ["Heidi LaRusso"],
    phone: "+1 212 555 0142",
    headquarters: { city: "New York", country: "United States", address: "350 Madison Ave, Suite 200" },
    portalUrl: "https://www.lushexperiences.com/trade",
    luxPagesId: "lp-rep-lush",
    luxPagesLastSynced: "2026-04-01T14:30:00.000Z",
    luxPagesLastVerified: "2026-02-10T00:00:00.000Z",
    socialMedia: {
      facebook: null,
      instagram: "https://www.instagram.com/example",
      linkedin: "https://www.linkedin.com/company/example",
    },
    contacts: [
      {
        name: "Heidi LaRusso",
        title: "Managing Director",
        email: "heidi@lushexperiences.com",
        phone: "+1 212 555 0142",
        photoUrl: "https://i.pravatar.cc/96?img=16",
      },
      {
        name: "Camille Durand",
        title: "Account Director · Caribbean",
        email: "camille@lushexperiences.com",
        phone: "+1 305 555 0199",
        photoUrl: null,
      },
    ],
  },
  "rf-index-select": {
    representativeNames: ["Tyler Lamont", "Danielle Dormand"],
    phone: "+1 646 555 0100",
    headquarters: { city: "New York", country: "United States", address: "One Penn Plaza" },
    portalUrl: "https://www.indexselect.com/login",
    contacts: [
      {
        name: "Tyler Lamont",
        title: "Partner",
        email: "tyler@indexselect.com",
        phone: "+1 646 555 0101",
        photoUrl: "https://i.pravatar.cc/96?img=12",
      },
      {
        name: "Danielle Dormand",
        title: "VP Sales",
        email: "danielle@indexselect.com",
        phone: "+1 646 555 0102",
        photoUrl: "https://i.pravatar.cc/96?img=9",
      },
    ],
  },
  "rf-nota-bene-global": {
    representativeNames: ["Alexandra Vaughn", "Isabel Grant"],
    phone: "+44 20 7946 0958",
    headquarters: { city: "London", country: "United Kingdom", address: "80 Strand, WC2R 0DE" },
    portalUrl: "https://trade.notabeneglobal.example/login",
    contacts: [
      {
        name: "Alexandra Vaughn",
        title: "Managing Director",
        email: "alexandra.v@notabeneglobal.com",
        phone: "+44 20 7946 0100",
        photoUrl: "https://i.pravatar.cc/96?img=5",
      },
      {
        name: "Isabel Grant",
        title: "Senior Sales · Americas",
        email: "isabel.g@notabeneglobal.com",
        phone: "+1 212 555 0777",
        photoUrl: null,
      },
    ],
  },
  "rf-janine-cifelli": {
    representativeNames: ["Janine Cifelli"],
    phone: "+1 212 555 0303",
    headquarters: { city: "New York", country: "United States", address: null },
    contacts: [
      {
        name: "Janine Cifelli",
        title: "Principal",
        email: "janine@janinecifelli.com",
        phone: "+1 212 555 0303",
        photoUrl: "https://i.pravatar.cc/96?img=47",
      },
      {
        name: "Reservations desk",
        title: "Trade support",
        email: "trade@janinecifelli.com",
        phone: "+1 212 555 0304",
        photoUrl: null,
      },
    ],
  },
  "rf-jmak": {
    representativeNames: ["John Makhmaltchi"],
    phone: "+1 310 555 0444",
    portalUrl: "https://www.jmak.com/advisors",
    contacts: [
      {
        name: "John Makhmaltchi",
        title: "President",
        email: "john@jmak.com",
        phone: "+1 310 555 0444",
        photoUrl: "https://i.pravatar.cc/96?img=33",
      },
    ],
  },
  "rf-muse-collection": {
    representativeNames: ["Vivian Chambers"],
    phone: "+44 20 555 0120",
    contacts: [
      {
        name: "Vivian Chambers",
        title: "Director",
        email: "vivian@muse-collection.com",
        phone: "+44 20 555 0120",
        photoUrl: "https://i.pravatar.cc/96?img=24",
      },
      {
        name: "Portfolio desk",
        title: "Sales coordination",
        email: "portfolio@muse-collection.com",
        phone: null,
        photoUrl: null,
      },
    ],
  },
  "rf-preferred-hotels-resorts": {
    representativeNames: ["Preferred Hotels trade desk"],
    phone: "+1 202 835 9862",
    headquarters: { city: "Washington", country: "United States", address: "655 15th St NW" },
    portalUrl: "https://www.preferredhotels.com/travel-advisors",
    contacts: [
      {
        name: "North America desk",
        title: "Luxury sales",
        email: "luxury.sales@preferredhotels.com",
        phone: "+1 202 835 9862",
        photoUrl: null,
      },
      {
        name: "Europe desk",
        title: "Trade partnerships",
        email: "europe@preferredhotels.com",
        phone: "+33 1 55 00 00 00",
        photoUrl: "https://i.pravatar.cc/96?img=60",
      },
    ],
  },
  "rf-the-dmc-collection": {
    representativeNames: ["James Okello", "Safari desk"],
    phone: "+254 20 555 0100",
    contacts: [
      {
        name: "James Okello",
        title: "Director · Africa",
        email: "safari@thedmccollection.com",
        phone: "+254 20 555 0100",
        photoUrl: "https://i.pravatar.cc/96?img=68",
      },
    ],
  },
  "rf-cruise-specialists-international": {
    representativeNames: ["Michael Chen", "Regent desk"],
    phone: "+1 800 555 0199",
    portalUrl: "https://www.cruisespecialists.example/trade",
    contacts: [
      {
        name: "Michael Chen",
        title: "Luxury cruise sales",
        email: "m.chen@cruisespecialists.example",
        phone: "+1 212 555 0900",
        photoUrl: "https://i.pravatar.cc/96?img=15",
      },
      {
        name: "Regent Seven Seas liaison",
        title: "Account team",
        email: "regent@cruisespecialists.example",
        phone: null,
        photoUrl: null,
      },
    ],
  },
};

function withDemoEnrichment(f: RepFirm): RepFirm {
  const patch = REP_FIRM_DEMO_PATCH[f.id];
  if (!patch) return f;
  return {
    ...f,
    ...patch,
    representativeNames: patch.representativeNames ?? f.representativeNames,
    specialty: f.specialty,
    regionsCovered: f.regionsCovered,
    contacts: patch.contacts ?? f.contacts,
    headquarters: patch.headquarters !== undefined ? patch.headquarters : f.headquarters,
    socialMedia: patch.socialMedia !== undefined ? patch.socialMedia : f.socialMedia,
  };
}

export const MOCK_REP_FIRMS: RepFirm[] = [...RAW_LEGACY_REP_FIRMS, ...RAW_KRISTIN_EXTRA].map((raw) =>
  withDemoEnrichment(migrateRepFirmRecord(raw))
);

export const MOCK_REP_FIRM_PRODUCT_LINKS: Record<string, RepFirmProductLink[]> = {
  prod_002: [
    {
      id: "rfl-prod-002-lush",
      repFirmId: "rf-lush-experiences",
      repFirmName: "LUSH Experiences",
      contactName: "Camille Durand",
      contactEmail: "camille@lushexperiences.com",
      scope: "enable",
      status: "active",
    },
  ],
  prod_003: [
    {
      id: "rfl-prod-003-dmc",
      repFirmId: "rf-the-dmc-collection",
      repFirmName: "The DMC Collection",
      contactName: "James Okello",
      contactEmail: "safari@thedmccollection.com",
      scope: "enable",
      status: "active",
    },
  ],
  prod_005: [
    {
      id: "rfl-prod-005-nota-bene",
      repFirmId: "rf-nota-bene-global",
      repFirmName: "Nota Bene Global",
      contactName: "Alexandra Vaughn",
      contactEmail: "alexandra.v@notabeneglobal.com",
      scope: "enable",
      status: "active",
    },
  ],
  prod_006: [
    {
      id: "rfl-prod-006-lush",
      repFirmId: "rf-lush-experiences",
      repFirmName: "LUSH Experiences",
      contactName: "Sofia Mendez",
      contactEmail: "sofia@lushexperiences.com",
      scope: "enable",
      status: "active",
    },
    {
      id: "rfl-prod-006-nota-bene",
      repFirmId: "rf-nota-bene-global",
      repFirmName: "Nota Bene Global",
      contactName: "Isabel Grant",
      contactEmail: "isabel.g@notabeneglobal.com",
      notes: "Covers UHNW direct bookings; coordinate with LUSH for chain-wide rate loads.",
      scope: "enable",
      status: "active",
      market: "Europe",
    },
  ],
  prod_008: [
    {
      id: "rfl-prod-008-csi",
      repFirmId: "rf-cruise-specialists-international",
      repFirmName: "Cruise Specialists International",
      contactName: "Michael Chen",
      contactEmail: "m.chen@cruisespecialists.example",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-villa-001": [
    {
      id: "rfl-prod-villa-kiwi",
      repFirmId: "rf-kiwi-collection",
      repFirmName: "Kiwi Collection",
      contactEmail: "trade@kiwicollection.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-rest-001": [
    {
      id: "rfl-prod-rest-traveller-made",
      repFirmId: "rf-traveller-made",
      repFirmName: "Traveller Made",
      contactName: "Reservation desk",
      contactEmail: "mice@travellermade.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-well-001": [
    {
      id: "rfl-prod-well-beyond-green",
      repFirmId: "rf-beyond-green",
      repFirmName: "Beyond Green",
      contactEmail: "wellness@staybeyondgreen.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-trans-001": [
    {
      id: "rfl-prod-trans-nota-bene",
      repFirmId: "rf-nota-bene-global",
      repFirmName: "Nota Bene Global",
      contactEmail: "aviation@notabeneglobal.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-amanvari": [
    {
      id: "rfl-prod-amanvari-preferred",
      repFirmId: "rf-preferred-hotels-resorts",
      repFirmName: "Preferred Hotels & Resorts",
      contactEmail: "luxury.sales@preferredhotels.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-waldorf-london": [
    {
      id: "rfl-prod-waldorf-slh",
      repFirmId: "rf-slh",
      repFirmName: "Small Luxury Hotels (SLH)",
      contactEmail: "traveltrade@slh.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-four-seasons-mykonos": [
    {
      id: "rfl-prod-fs-mykonos-lhw",
      repFirmId: "rf-lhw",
      repFirmName: "Leading Hotels of the World (LHW)",
      contactEmail: "advisors@lhw.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-six-senses-london": [
    {
      id: "rfl-prod-six-senses-slh",
      repFirmId: "rf-slh",
      repFirmName: "Small Luxury Hotels (SLH)",
      contactEmail: "traveltrade@slh.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-orient-express-venezia": [
    {
      id: "rfl-prod-orient-preferred",
      repFirmId: "rf-preferred-hotels-resorts",
      repFirmName: "Preferred Hotels & Resorts",
      contactEmail: "europe@preferredhotels.com",
      scope: "enable",
      status: "active",
    },
  ],
  "prod-seven-seas-prestige": [
    {
      id: "rfl-prod-seven-seas-csi",
      repFirmId: "rf-cruise-specialists-international",
      repFirmName: "Cruise Specialists International",
      contactName: "Regent desk",
      contactEmail: "regent@cruisespecialists.example",
      scope: "enable",
      status: "active",
    },
  ],
};

export function getRepFirmLinksForProduct(productId: string): RepFirmProductLink[] {
  return MOCK_REP_FIRM_PRODUCT_LINKS[productId] ?? [];
}

export function getRepFirmById(id: string): RepFirm | undefined {
  return MOCK_REP_FIRMS.find((f) => f.id === id);
}

/** Prefer live registry (Products / Settings); fall back to seed mock. */
export function getRepFirmByIdWithOverlay(id: string, overlay?: RepFirm[] | null): RepFirm | undefined {
  if (overlay?.length) {
    const hit = overlay.find((f) => f.id === id);
    if (hit) return hit;
  }
  return getRepFirmById(id);
}
